project:
  type: website

website:
  title: "Christian Smith"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: work_exp.qmd
        text: Work Experience
      - href: projects.qmd
        text: Projects
      - href: education.qmd
        text: Education

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



